# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyperspell" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "303fb17725bef1761d65447eebda574ba6e1e0648c4400f8e7904158d231e78e"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "6eeb718125c80b598c95644de20b515e826c3395ef936939c272697aa062530b"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "13eb95934c2683fc14fa1e150b38e7db51d639b05aebfe331ab13135ccb76d0f"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb93233e2af5bb2431fed43f0d2a78caa647f98cd964be160ca117e1241100df"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hyperspell"
  desc "Official Hyperspell CLI to give agents memory and context"
  homepage "https://hyperspell.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hyperspell"
  manpage "man/man1/hyperspell.1.gz"
  bash_completion "completions/hyperspell.bash"
  fish_completion "completions/hyperspell.fish"
  zsh_completion "completions/hyperspell.zsh"

  # No zap stanza required

end
