# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyperspell" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_macos_amd64.zip"
      sha256 "6acaa3a9a3735b5847b3907a9fcf91a11f4e986accbcde18e06ab86c97d9b769"
    end
    on_arm do
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_macos_arm64.zip"
      sha256 "6f418c871c8387555740634d5af68d044083bb24971c5af81c5798bd9a90c574"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_linux_amd64.tar.gz"
      sha256 "018e0ab9330f175c00e4af350a7508940d896a17cbd4dd5dab7217fb20731be6"
    end
    on_arm do
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_linux_arm64.tar.gz"
      sha256 "78e7c987ce825d96ecbad4f8a3150a9d2708917a6d8bda10df2a4d91b95a7a33"
    end
  end

  name "hyperspell"
  desc "Offical Hyperspell CLI to give agents memory and contect"
  homepage "https://hyperspell.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hyperspell"
  manpage "man/man1/hyperspell.1.gz"
  bash_completion "completions/hyperspell.bash"
  fish_completion "completions/hyperspell.fish"
  zsh_completion "completions/hyperspell.zsh"

  # No zap stanza required

end
