# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyperspell" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "adcb79ac7136afbb9c00c1df26446cd6631c6055a555f5dd0629a1c778964f1e"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_macos_arm64.zip"
    end
    on_intel do
      sha256 "a6231b1d851511350d1241e3f85fb44e9a7c7d29981fbe53d6c986e71887d702"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_macos_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "9380b4ebc1d7dfb704f302a9055605c6fb860317e074bad7523eab8685da21a8"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "af1ea686696383378dac49f6cc8e19eee73a85a49bc749fc3a6458d14ca2ce04"
      url "https://github.com/hyperspell/hyperspell-cli/releases/download/v#{version}/hyperspell_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hyperspell"
  desc "Official Hyperspell CLI to give agents memory and context"
  homepage "https://hyperspell.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hyperspell"
  manpage "man/man1/hyperspell.1.gz"
  bash_completion "completions/hyperspell.bash"
  fish_completion "completions/hyperspell.fish"
  zsh_completion "completions/hyperspell.zsh"

  # No zap stanza required
end
